name: Build Android

on:
  workflow_dispatch: # Add manual trigger here

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kuala_Lumpur # Set time zone globally
    if: github.ref == 'refs/heads/master'

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # 4. Set up JDK 17 for Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Use Eclipse Adoptium JDK (Temurin)

      # 5. Set up the environment variables using .env
      - name: Set Environment Variables
        run: |
          echo "API_URL_ANDROID=https://awttechsolution.com/mobile/api" >> .env
          echo "API_URL_IOS=https://awttechsolution.com/mobile/api" >> .env

      # 6. Debug `.env` File
      - name: Debug .env File
        run: cat .env

      # 7. Build APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # 8. Rename APK
      - name: Rename APK
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          TIMESTAMPED_APK="poppmobile-${TIMESTAMP}.apk"
          mv android/app/build/outputs/apk/release/app-release.apk \
             android/app/build/outputs/apk/release/$TIMESTAMPED_APK
          echo "APK_NAME=$TIMESTAMPED_APK" >> $GITHUB_ENV

      # 9. Upload APK as an artifact
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APK_NAME }}
          path: android/app/build/outputs/apk/release/${{ env.APK_NAME }}
