name: Push to Release Branch

on:
  push:
    branches:
      - master # Detect changes to master

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Create and push the `release` branch
      - name: Create Release Branch
        run: |
          git checkout -b release
          git push origin release
